// Auto-generated by mercure_ui UI designer
// UI navigation/state machine only (no setup/loop, no hardware init).

#pragma once

#include <stdint.h>

// Forward declaration (definition lives in generated_screens.h).
enum class UiScreen : uint8_t;

// IMPORTANT: must match the gazepoint firmware button names exactly.
enum class Button : uint8_t {
    BTN_UP,
    BTN_DOWN,
    BTN_LEFT,
    BTN_RIGHT,
    BTN_CENTER,
    BTN_A,
    BTN_B
};

void ui_sm_init();
void ui_sm_on_button(Button btn);
UiScreen ui_sm_get_screen();
// Allow firmware/serial commands to override the current screen.
void ui_sm_set_screen(UiScreen screen);

