#pragma once

// Auto-generated by mercure_ui UI designer.
// Target: 128x64 SSD1306 using Adafruit_SSD1306 + Adafruit_GFX.
// NOTE: draw_*_screen() functions do NOT call display.display().
// Call display.display() once per frame after draw_screen(...).

#include <Arduino.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

static const uint8_t UI_DESIGNER_W = 128;
static const uint8_t UI_DESIGNER_H = 64;

// Available screens (auto-generated).
enum class UiScreen : uint8_t {
  BOOT = 0,
  POSITION = 1,
  CALIBRATION = 2,
  RECORDING = 3,
  MONITOR_POS = 4,
  MONITOR_GAZE = 5,
  RESULTS = 6,
};

// Dynamic element variables (auto-generated).
// Update these values at runtime before calling draw_*_screen() / draw_screen().
static bool ui_tracker_detected = true;
static bool ui_led_detected = false;
static bool ui_connection = true;
static bool ui_calibration_ok = false;

// Dynamic variables (auto-generated).
enum class UiDynamicVar : uint8_t {
  UI_TRACKER_DETECTED,
  UI_LED_DETECTED,
  UI_CONNECTION,
  UI_CALIBRATION_OK,
};

// Generic fallback: unknown types/vars return default and do nothing.
template <typename T> inline T ui_get(UiDynamicVar) { return T(); }
template <typename T> inline void ui_set(UiDynamicVar, const T &) {}

template <> inline bool ui_get<bool>(UiDynamicVar var) {
  switch (var) {
    case UiDynamicVar::UI_TRACKER_DETECTED: return ui_tracker_detected;
    case UiDynamicVar::UI_LED_DETECTED: return ui_led_detected;
    case UiDynamicVar::UI_CONNECTION: return ui_connection;
    case UiDynamicVar::UI_CALIBRATION_OK: return ui_calibration_ok;
    default: return false;
  }
}
template <> inline void ui_set<bool>(UiDynamicVar var, const bool &value) {
  switch (var) {
    case UiDynamicVar::UI_TRACKER_DETECTED: ui_tracker_detected = value; break;
    case UiDynamicVar::UI_LED_DETECTED: ui_led_detected = value; break;
    case UiDynamicVar::UI_CONNECTION: ui_connection = value; break;
    case UiDynamicVar::UI_CALIBRATION_OK: ui_calibration_ok = value; break;
    default: break;
  }
}

template <> inline String ui_get<String>(UiDynamicVar var) {
  switch (var) {
    default: return String("");
  }
}
template <> inline void ui_set<String>(UiDynamicVar var, const String &value) {
  switch (var) {
    default: break;
  }
}

// Screen 0: boot
inline void draw_boot_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(23, 8);
  display.print(F("PLEASE WAIT..."));
  display.drawRect(41, 25, 8, 8, SSD1306_WHITE);
  if (ui_tracker_detected) {
    display.drawLine(43, 29, 43, 30, SSD1306_WHITE);
    display.drawLine(43, 30, 46, 27, SSD1306_WHITE);
  }
  display.drawRect(41, 39, 8, 8, SSD1306_WHITE);
  if (ui_led_detected) {
    display.drawLine(43, 43, 43, 44, SSD1306_WHITE);
    display.drawLine(43, 44, 46, 41, SSD1306_WHITE);
  }
  display.drawRect(41, 52, 8, 8, SSD1306_WHITE);
  if (ui_connection) {
    display.drawLine(43, 56, 43, 57, SSD1306_WHITE);
    display.drawLine(43, 57, 46, 54, SSD1306_WHITE);
  }
  // PLACEHOLDER region: x=8, y=29, w=24, h=22
  // TODO: add custom drawing code here
  // Example: display.drawBitmap(...);
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(53, 25);
  display.print(F("Eye tracker"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(54, 39);
  display.print(F("LED"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(54, 52);
  display.print(F("Connection"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(41, 0);
  display.print(F("LOADING"));
}

// Screen 1: position
inline void draw_position_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.drawRect(40, 2, 48, 16, SSD1306_WHITE);
  {
    const int x1 = 79, y1 = 16, x2 = 88, y2 = 50;
    const int dx = x2 - x1;
    const int dy = y2 - y1;
    const int n = max(abs(dx), abs(dy));
    if (n == 0) {
      display.drawPixel(x1, y1, SSD1306_WHITE);
    } else {
      for (int i = 0; i <= n; i++) {
        if (((i / 2) % 2) != 0) continue; // 2 on, 2 off
        const int px = x1 + (dx * i) / n;
        const int py = y1 + (dy * i) / n;
        display.drawPixel(px, py, SSD1306_WHITE);
      }
    }
  }
  {
    const int x1 = 40, y1 = 48, x2 = 48, y2 = 16;
    const int dx = x2 - x1;
    const int dy = y2 - y1;
    const int n = max(abs(dx), abs(dy));
    if (n == 0) {
      display.drawPixel(x1, y1, SSD1306_WHITE);
    } else {
      for (int i = 0; i <= n; i++) {
        if (((i / 2) % 2) != 0) continue; // 2 on, 2 off
        const int px = x1 + (dx * i) / n;
        const int py = y1 + (dy * i) / n;
        display.drawPixel(px, py, SSD1306_WHITE);
      }
    }
  }
  {
    const int x1 = 33, y1 = 46, x2 = 95, y2 = 47;
    const int dx = x2 - x1;
    const int dy = y2 - y1;
    const int n = max(abs(dx), abs(dy));
    if (n == 0) {
      display.drawPixel(x1, y1, SSD1306_WHITE);
    } else {
      for (int i = 0; i <= n; i++) {
        if (((i / 2) % 2) != 0) continue; // 2 on, 2 off
        const int px = x1 + (dx * i) / n;
        const int py = y1 + (dy * i) / n;
        display.drawPixel(px, py, SSD1306_WHITE);
      }
    }
  }
  {
    const int x1 = 42, y1 = 21, x2 = 84, y2 = 22;
    const int dx = x2 - x1;
    const int dy = y2 - y1;
    const int n = max(abs(dx), abs(dy));
    if (n == 0) {
      display.drawPixel(x1, y1, SSD1306_WHITE);
    } else {
      for (int i = 0; i <= n; i++) {
        if (((i / 2) % 2) != 0) continue; // 2 on, 2 off
        const int px = x1 + (dx * i) / n;
        const int py = y1 + (dy * i) / n;
        display.drawPixel(px, py, SSD1306_WHITE);
      }
    }
  }
  display.drawCircle(64, 34, 11, SSD1306_WHITE);
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(13, 53);
  display.print(F("START CALIBRATION"));
  display.drawRoundRect(8, 51, 112, 11, 3, SSD1306_WHITE);
}

// Screen 2: calibration
inline void draw_calibration_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(13, 2);
  display.print(F("CALIBRATION CHECK"));
  // Calibration OK checkbox (driven by ui_calibration_ok)
  display.drawRect(116, 2, 8, 8, SSD1306_WHITE);
  if (ui_calibration_ok) {
    display.drawLine(118, 6, 118, 7, SSD1306_WHITE);
    display.drawLine(118, 7, 121, 4, SSD1306_WHITE);
  }
  display.setTextSize(2);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(45, 22);
  display.print(F("READY"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(18, 51);
  display.print(F("START RECORDING"));
  display.drawCircle(29, 30, 8, SSD1306_WHITE);
  display.drawLine(23, 30, 26, 35, SSD1306_WHITE);
  display.drawLine(26, 35, 35, 25, SSD1306_WHITE);
  display.drawRoundRect(15, 48, 97, 13, 3, SSD1306_WHITE);
}

// Screen 3: recording
inline void draw_recording_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(19, 0);
  display.print(F("MARKER STATUS:"));
  display.setTextSize(2);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(1, 23);
  display.print(F("MARKERS"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(66, 11);
  display.print(F(" END"));
  display.setTextSize(1);
  display.fillRect(36, 11, 30, 8, SSD1306_WHITE);
  display.setTextColor(SSD1306_BLACK);
  display.setCursor(36, 11);
  display.print(F("START"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(15, 50);
  display.print(F("REC"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(40, 50);
  display.print(F("STOP RECORDING"));
  display.setTextSize(2);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(94, 23);
  display.print(F("03"));
  display.fillCircle(9, 54, 4, SSD1306_WHITE);
  display.drawRoundRect(38, 48, 88, 11, 3, SSD1306_WHITE);
}

// Screen 4: Monitor_pos
inline void draw_monitor_pos_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 0);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 9);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 17);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 26);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 35);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 44);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 53);
  display.print(F("Monitoring pos"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 0);
  display.print(F("TEXT"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 9);
  display.print(F("TEXT"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 18);
  display.print(F("TEXT"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 27);
  display.print(F("TEXT"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 36);
  display.print(F("TEXT"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 45);
  display.print(F("TEXT"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(93, 54);
  display.print(F("TEXT"));
}

// Screen 5: Monitor_gaze
inline void draw_monitor_gaze_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.setTextSize(2);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(30, 2);
  display.print(F("TITRE"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 19);
  display.print(F("Monitoring gaze"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 28);
  display.print(F("Monitoring gaze"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 37);
  display.print(F("Monitoring gaze"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 46);
  display.print(F("Monitoring gaze"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(4, 55);
  display.print(F("Monitoring gaze"));
}

// Screen 6: results
inline void draw_results_screen(Adafruit_SSD1306 &display) {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(37, 0);
  display.print(F("RESULTS"));
  display.drawRoundRect(2, 8, 125, 55, 3, SSD1306_WHITE);
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(7, 12);
  display.print(F("RESULTS"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(7, 22);
  display.print(F("RESULTS"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(7, 32);
  display.print(F("RESULTS"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(7, 42);
  display.print(F("RESULTS"));
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(7, 52);
  display.print(F("RESULTS"));
}

// Dispatcher: choose which screen to draw from your main loop.
inline void draw_screen(Adafruit_SSD1306 &display, UiScreen screen) {
  switch (screen) {
    case UiScreen::BOOT: draw_boot_screen(display); break;
    case UiScreen::POSITION: draw_position_screen(display); break;
    case UiScreen::CALIBRATION: draw_calibration_screen(display); break;
    case UiScreen::RECORDING: draw_recording_screen(display); break;
    case UiScreen::MONITOR_POS: draw_monitor_pos_screen(display); break;
    case UiScreen::MONITOR_GAZE: draw_monitor_gaze_screen(display); break;
    case UiScreen::RESULTS: draw_results_screen(display); break;
    default: draw_boot_screen(display); break;
  }
}

// Optional: legacy index-based dispatcher (maps to UiScreen values).
inline void draw_screen(Adafruit_SSD1306 &display, uint8_t index) {
  draw_screen(display, static_cast<UiScreen>(index));
}
