// Auto-generated by mercure_ui UI designer
// UI navigation/state machine only (no setup/loop, no hardware init).

#include "ui_state_machine.h"
#include "generated_screens.h"

// The current screen (required by integration API).
static UiScreen g_screen = UiScreen::BOOT;

static UiScreen next_in_main_flow(UiScreen s) {
    switch (s) {
        case UiScreen::BOOT: return UiScreen::FIND_POSITION;
        case UiScreen::FIND_POSITION: return UiScreen::MOVE_CLOSER;
        case UiScreen::MOVE_CLOSER: return UiScreen::MOVE_FARTHER;
        case UiScreen::MOVE_FARTHER: return UiScreen::IN_POSITION;
        case UiScreen::IN_POSITION: return UiScreen::CALIBRATION;
        case UiScreen::CALIBRATION: return UiScreen::RECORD_CONFIRMATION;
        case UiScreen::RECORD_CONFIRMATION: return UiScreen::RECORDING;
        case UiScreen::RECORDING: return UiScreen::STOP_RECORD;
        case UiScreen::STOP_RECORD: return UiScreen::INFERENCE_LOADING;
        case UiScreen::INFERENCE_LOADING: return UiScreen::RESULTS;
        default: return s;
    }
}

void ui_sm_init() {
    g_screen = UiScreen::BOOT;
}

void ui_sm_on_button(Button btn) {
    switch (btn) {
        case Button::BTN_RIGHT:
            g_screen = next_in_main_flow(g_screen);
            break;
        case Button::BTN_A:
            g_screen = UiScreen::FIND_POSITION;
            break;
        case Button::BTN_B:
            g_screen = UiScreen::MONITORING;
            break;
        default:
            // TODO: add behavior for other buttons (UP/DOWN/LEFT/CENTER).
            break;
    }
}

UiScreen ui_sm_get_screen() {
    return g_screen;
}

void ui_sm_set_screen(UiScreen screen) {
    g_screen = screen;
}

